### ISSUE TITLE
Build Errors on Packaging

### ISSUE THREAD

**Issue by Starkium** [truefranco/UnrealEngine-MetaXR-5.1#1]
There are a lot of linker errors. Not sure what is missing.

`PackagingResults: Error: undefined symbol: __aarch64_swp8_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_ldadd4_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_ldadd4_relax
PackagingResults: Error: undefined symbol: __aarch64_cas4_relax
PackagingResults: Error: undefined symbol: __aarch64_ldadd4_rel
PackagingResults: Error: undefined symbol: __aarch64_cas4_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_ldadd8_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_cas8_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_ldset8_rel
PackagingResults: Error: undefined symbol: __aarch64_ldadd4_acq
PackagingResults: Error: undefined symbol: __aarch64_cas8_relax
PackagingResults: Error: undefined symbol: __aarch64_cas8_acq
PackagingResults: Error: undefined symbol: __aarch64_ldset8_acq
PackagingResults: Error: undefined symbol: __aarch64_ldset8_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_ldadd8_relax
PackagingResults: Error: undefined symbol: __aarch64_cas8_rel
PackagingResults: Error: undefined symbol: __aarch64_ldset4_rel
PackagingResults: Error: undefined symbol: __aarch64_swp1_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_cas1_acq_rel
PackagingResults: Error: undefined symbol: __aarch64_swp4_acq_rel
PackagingResults: Error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: Unknown Error`

**Comment by truefranco** [comment]
You need NDK r25b for Android ;)
