### ISSUE TITLE
Patch for software occlusion culling, applicable to 5.2+

### ISSUE THREAD

**Issue by motorsep** [truefranco/UnrealEngine-MetaXR-5.1#2]
5.2 Meta fork is out and I am wondering maybe you could make a clean patch for software occlusion culling only, that can be applied to Meta's fork 5.2 and newer ?

**Comment by truefranco** [comment]
There you go, apply the patch to the Oculus fork 5.2.
[occlusion.patch](https://github.com/truefranco/UnrealEngine-MetaXR-5.1/files/12704726/occlusion.patch)

**Comment by truefranco** [comment]
There you go, apply to Oculus fork 5.2.
[occlusion.patch](https://github.com/truefranco/UnrealEngine-MetaXR-5.1/files/12704805/occlusion.patch)
